version: '3'
services:
  techlab-amazon-develop:
    build: ./techlab-amazon-develop
    container_name: techlab-amazon-develop
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
    networks:
        - microservices-network

  techlab-paypal-develop:
    build: ./techlab-paypal-develop
    container_name: techlab-paypal-develop
    hostname: techlab-paypal-develop
    ports:
      - "8081:8081"
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
    networks:
      - microservices-network

  techlab-visa-develop:
    build: ./techlab-visa-develop
    container_name: techlab-visa-develop
    hostname: techlab-visa-develop
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
    networks:
      - microservices-network

  consul-server:
    container_name: consul-server
    image: consul:1.14.8
    hostname: consul-server
    ports:
      - "8500:8500"
    command: 'agent -server -bootstrap-expect=1 -ui -bind=0.0.0.0 -client=0.0.0.0'
    networks:
      - microservices-network


  techlab-pms-develop:
      build: ./techlab-pms-develop
      container_name: techlab-pms-develop
      depends_on:
        - techlab-amazon-develop
        - techlab-paypal-develop
        - techlab-visa-develop
      links:
        - fluentd
      logging:
        driver: "fluentd"
        options:
          fluentd-address: localhost:24224
      ports:
        - "8080:8080"
      networks:
        - microservices-network

  techlab-ugo:
      build: ./techlab-ugo
      links:
        - fluentd
      logging:
        driver: "fluentd"
        options:
          fluentd-address: localhost:24224
      networks:
        - microservices-network

  techlab-ewallet:
    build: ./techlab-ewallet
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
    networks:
      - microservices-network

  postgres:
    image: postgres
    container_name: postgres-db
    hostname: postgres
    environment:
      POSTGRES_DB: ugo, ewallet, pms
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    networks:
      - microservices-network

  fluentd:
    image: fluentd:latest
    hostname: fluentd
    volumes:
      - ${HOME}/fluentd/fluent.conf:/fluentd/etc/fluent.conf
    environment:
      HOME: /home/bolot
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge