version: '3'
services:
  techlab-amazon-develop:
    build: ./techlab-amazon-develop
    container_name: techlab-amazon-develop
    networks:
      - microservices-network

  techlab-paypal-develop:
    build: ./techlab-paypal-develop
    container_name: techlab-paypal-develop
    networks:
      - microservices-network

  techlab-visa-develop:
    build: ./techlab-visa-develop
    container_name: techlab-visa-develop
    hostname: techlab-visa-develop
    networks:
      - microservices-network

  consul-server:
    container_name: consul-server
    image: consul:1.14.8
    hostname: consul-server
    ports:
      - "8500:8500"
    command: 'agent -server -bootstrap-expect=1 -ui -bind=0.0.0.0 -client=0.0.0.0'
    networks:
      - microservices-network

  techlab-pms-develop:
    build: ./techlab-pms-develop
    container_name: techlab-pms-develop
    ports:
      - "8080:8080"
    depends_on:
      - techlab-amazon-develop
      - techlab-paypal-develop
      - techlab-visa-develop
    networks:
      - microservices-network

  techlab-ugo:
    build: ./techlab-ugo
    networks:
      - microservices-network

  techlab-ewallet:
    build: ./techlab-ewallet
    ports:
      - "8203:8203"
      - "5005:5005"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - microservices-network

  postgres:
    build: ./techlab-ewallet/ewl-liquibase/docker
    ports:
      - "5432:5432"
    restart: always
    container_name: ewl-DB
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge