version: '3'
services:
  techlab-pms-develop:
    build: ./techlab-pms-develop
    container_name: techlab-pms-develop

  techlab-amazon-develop:
    build: ./techlab-amazon-develop
    container_name: techlab-amazon-develop

  techlab-paypal-develop:
    build: ./techlab-paypal-develop
    container_name: techlab-paypal-develop

  techlab-visa-develop:
    build: ./techlab-visa-develop
    container_name: techlab-visa-develop