version: '3'
services:
  techlab_amazon:
    build: ./techlab-amazon-develop
    container_name: techlab_amazon
    hostname: amazon
    depends_on:
      - logstash
      - consul_server
    networks:
      - microservices-network
    logging:
      driver: gelf
      options:
        tag : techlab-amazon-develop
        gelf-address: udp://localhost:12201

  techlab_paypal:
    build: ./techlab-paypal-develop
    container_name: techlab_paypal
    hostname: paypal
    depends_on:
      - logstash
      - consul_server
    networks:
      - microservices-network
    logging:
      driver: gelf
      options:
        tag : techlab-paypal-develop
        gelf-address: udp://localhost:12201

  techlab_visa:
    build: ./techlab-visa-develop
    container_name: techlab_visa
    hostname: visa
    depends_on:
      - logstash
      - consul_server
    networks:
      - microservices-network
    logging:
      driver: gelf
      options:
        tag : techlab-visa-develop
        gelf-address: udp://localhost:12201

  techlab_pms:
    build: ./techlab-pms-develop
    container_name: techlab_pms
    hostname: techlab-pms-develop
    depends_on:
      - techlab_amazon
      - techlab_paypal
      - techlab_visa
      - consul_server
    networks:
      - microservices-network

  consul_server:
    container_name: consul
    image: consul:1.15.2
    hostname: consul
    ports:
      - "8500:8500"
    command: 'agent -server -bootstrap-expect=1 -ui -bind=0.0.0.0 -client=0.0.0.0'
    networks:
      - microservices-network

  techlab_fe:
    build: techlab_fe
    container_name: techlab_fe
    ports:
      - "3000:3000"
    depends_on:
      - logstash
    networks:
      - microservices-network
    logging:
      driver: gelf
      options:
        tag: techlab_fe
        gelf-address: udp://localhost:12201

  techlab_ugo:
    build: ./techlab-ugo
    container_name: techlab_ugo
    hostname: techlab-ugo
    ports:
      - "8200:8200"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres?currentSchema=ugo
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_DATASOURCE_DRIVER_CLASS: org.postgresql.Driver
    depends_on:
      - postgres
    networks:
      - microservices-network
    logging:
      driver: gelf
      options:
        tag : techlab-ugo
        gelf-address: udp://localhost:12201

  techlab_ewallet:
    build: ./techlab-ewallet
    container_name: techlab_ewallet
    hostname: techlab-ewallet
    ports:
      - "8203:8203"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres?currentSchema=techlab_ewl
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_DATASOURCE_DRIVER_CLASS: org.postgresql.Driver
    depends_on:
      - postgres
    networks:
      - microservices-network
    logging:
      driver: gelf
      options:
        tag : techlab_ewallet
        gelf-address: udp://localhost:12201

  logstash:
    image: docker.elastic.co/logstash/logstash:7.16.3
    container_name: logstash
    hostname: logstash
    volumes:
      - ./logstash-config:/usr/share/logstash/pipeline
      - ./logs:/usr/share/logstash/logs  # Mount logs directory
    ports:
      - "5000:5000"  # Adjust the port as needed
    networks:
      - microservices-network
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201

  postgres:
    build: ./techlab-ewallet/ewl-liquibase/docker
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: postgres
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge