version: '3'
services:
  techlab-amazon-develop:
    build: ./techlab-amazon-develop
    container_name: techlab-amazon-develop
    depends_on:
      - logstash
    networks:
      - microservices-network

  techlab-paypal-develop:
    build: ./techlab-paypal-develop
    container_name: techlab-paypal-develop
    depends_on:
      - logstash
    networks:
      - microservices-network

  techlab-visa-develop:
    build: ./techlab-visa-develop
    container_name: techlab-visa-develop
    hostname: techlab-visa-develop
    depends_on:
      - logstash
    networks:
      - microservices-network

  techlab-pms-develop:
    build: ./techlab-pms-develop
    container_name: techlab-pms-develop
    ports:
      - "8080:8080"
    depends_on:
      - techlab-amazon-develop
      - techlab-paypal-develop
      - techlab-visa-develop
      - logstash
    networks:
      - microservices-network

  consul-server:
    container_name: consul-server
    image: consul:1.14.8
    hostname: consul-server
    ports:
      - "8500:8500"
    command: 'agent -server -bootstrap-expect=1 -ui -bind=0.0.0.0 -client=0.0.0.0'
    networks:
      - microservices-network

  techlab-fe-mock-node:
    build: ./techlab-fe-mock-node
    ports:
      - "3000:3000"
    depends_on:
      - logstash
    networks:
      - microservices-network

  techlab-ugo:
    build: ./techlab-ugo
    container_name: techlab-ugo
    hostname: techlab-ugo
    ports:
      - "8200:8200"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres?currentSchema=ugo
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_DATASOURCE_DRIVER_CLASS: org.postgresql.Driver
    depends_on:
      - postgres
    networks:
      - microservices-network

  techlab-ewallet:
    build: ./techlab-ewallet
    container_name: techlab-ewallet
    hostname: techlab-ewallet
    ports:
      - "8203:8203"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres?currentSchema=techlab_ewl
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_DATASOURCE_DRIVER_CLASS: org.postgresql.Driver
    depends_on:
      - postgres
    networks:
      - microservices-network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.16.3
    container_name: logstash
    hostname: logstash
    volumes:
      - ./logstash-config:/usr/share/logstash/pipeline
      - ./logs:/usr/share/logstash/logs  # Mount logs directory
    ports:
      - "5000:5000"  # Adjust the port as needed
    networks:
      - microservices-network

  postgres:
    build: ./techlab-ewallet/ewl-liquibase/docker
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: postgres
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge