eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  server:
    port: 8761
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.server.port}/eureka/